[features]
seeds = false
skip-lint = false

[programs.devnet]
devolt = "3UMz3ZmnruockoaMSqAYw22VkUgxDq4qdMa3A5WzQ3P1"

[registry]
url = "http://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/marcelofeitoza/.config/solana/id.json"

[scripts]
test = "yarn anchor-tests"
