[features]
seeds = false
skip-lint = false

[programs.devnet]
devolt = "EWQ3cdo7pHZnmuubzDMAdso5U8nAwbhrAeSKuEw9R2mg"

[registry]
url = "http://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/marcelofeitoza/.config/solana/id.json"

[scripts]
test = "yarn anchor-tests"
